### ISSUE TITLE
Error in Redmine 4.1.3

### ISSUE THREAD

**Issue by koren85** [easyredmine/redmine_entity_generator#16]
Hi,
I I'm having problems creating a new entity, creating custom fields doesn't work

````
The single-table inheritance mechanism failed to locate the subclass: 'NewEntityNameCustomField'. This error is raised because the column 'type' is reserved for storing the class in case of inheritance. Please rename this column if you didn't intend it to be used for storing the inheritance class or overwrite CustomField.inheritance_column to use another column for that information.

ActiveRecord::SubclassNotFound (The single-table inheritance mechanism failed to locate the subclass: 'NewEntityNameCustomField'. This error is raised because the column 'type' is reserved for storing the class in case of inheritance. Please rename this column if you didn't intend it to be used for storing the inheritance class or overwrite CustomField.inheritance_column to use another column for that information.):

app/controllers/custom_fields_controller.rb:32:in `group_by'
app/controllers/custom_fields_controller.rb:32:in `block (2 levels) in index'
app/controllers/custom_fields_controller.rb:30:in `index'
lib/redmine/sudo_mode.rb:65:in `sudo_mode'

```
`

**Comment by koren85** [comment]
omg, https://www.easyredmine.com/ru/chastye-voprosy/baza-znanij?view=knowledge_detail&id=166&category_id=48
